# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwo < Formula
  desc "Git Workspace companion CLI"
  homepage "https://gitwo.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.1/gitwo_0.2.1_darwin_amd64.tar.gz"
      sha256 "61a70f34a34ca9f91217b6ec15f40fb18afe0d63cb2320ef1c8ebf5de51c1aad"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.1/gitwo_0.2.1_darwin_arm64.tar.gz"
      sha256 "4977a375eb30975d2849f8bb45abbe8d1e78d833df21e04b8388463d26a4af69"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.1/gitwo_0.2.1_linux_amd64.tar.gz"
      sha256 "6465f9e384f5adf284dcad05627ad9f38c6c58b685fa08ec4ac58d67a271a9e1"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.1/gitwo_0.2.1_linux_arm64.tar.gz"
      sha256 "dac6e3891a226b48884d3cffee270c0ee2e3c80e04049b5f959e8c7f3008a2b7"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  test do
    system "#{bin}/gitwo", "--version"
  end
end
