# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwo < Formula
  desc "Git Workspace companion CLI"
  homepage "https://gitwo.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.0/gitwo_0.2.0_darwin_amd64.tar.gz"
      sha256 "8093b790ede8106b83545ade09f3114f40724537d870f911f5f64d1d8c4f3415"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.0/gitwo_0.2.0_darwin_arm64.tar.gz"
      sha256 "d1552c2d0fcc4716e780ec12199f43cefbd6b97b174351964ad6cff8ab31eac9"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.0/gitwo_0.2.0_linux_amd64.tar.gz"
      sha256 "481ece76a232644c08f69b3bd56ed8fc89d17129ce830905cb3e9c049bd7431d"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.2.0/gitwo_0.2.0_linux_arm64.tar.gz"
      sha256 "87a018be44d3f288a690e6800b4ad7aa0c81606ea709dd97851a2cdd8d185efc"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  test do
    system "#{bin}/gitwo", "--version"
  end
end
