# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwo < Formula
  desc "Git Workspace companion CLI"
  homepage "https://gitwo.dev"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.1.5/gitwo_0.1.5_darwin_amd64.tar.gz"
      sha256 "e4ecda0205cf57bf28352ff7e65c8cfd1b150c8e8106c2e48203335d6f942908"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.1.5/gitwo_0.1.5_darwin_arm64.tar.gz"
      sha256 "b0eddae2c91f0fa2392d590ac2dd25833d106087bf2c1f9f0b290ea1786fe32b"

      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.1.5/gitwo_0.1.5_linux_amd64.tar.gz"
      sha256 "ca236eeb2c519db703839fa9688489c26f3c9a69eeb5f5f35c63f180a99aa027"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/gitwohq/gitwo/releases/download/v0.1.5/gitwo_0.1.5_linux_arm64.tar.gz"
      sha256 "2d549eed2e8a9a0e7e78b424ea75162a6ce767f795d4ddfcfa0d75725548c04e"
      def install
        bin.install "gitwo"
        # Ship pre-generated shell completions from the archive:
        bash_completion.install "completions/gitwo.bash" => "gitwo"
        zsh_completion.install  "completions/gitwo.zsh"  => "_gitwo"
        fish_completion.install "completions/gitwo.fish" => "gitwo.fish"
      end
    end
  end

  test do
    system "#{bin}/gitwo", "--version"
  end
end
